### ISSUE TITLE
Conflict correction with ESlint

### ISSUE THREAD

**Issue by lineuxyz** [BrasilNaLinha/core-api#9]
# Conflict correction with ESlint

## Labels
 
- bug

## About

It is necessary to find what is conflicting with ESlint so that it can correct syntax errors and leave the code all organized and standardized

---

## User Story

Checking conflicting files / settings

Syntax check error

Keep the code organized and standardized among everyone on the team

---

**Comment by evertoncastro** [comment]
Hi Lineu, what is the node version you are using locally?

**Comment by lineuxyz** [comment]
13.12.0
